project:
  type: website
  output-dir: docs

website:
  title: "Ramu Nalla"       # <--- CHANGE THIS (Was "")
  favicon: favicon.svg
  navbar:
    background: primary     # Add this line to ensure the navbar has a background color
    search: false
    right:
      - text: "About"
        href: index.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - icon: github
        href: https://github.com/RamuNalla
        target: _blank
      - icon: linkedin
        href: https://linkedin.com/in/ramu-nalla-2959b8b3/
        target: _blank

format:
  html:
    theme: [cosmo, custom.scss]
    fontsize: 1rem
    mainfont: "Georgia"
    link-color: "#5a9fd4"
    highlight-style: dracula
    toc: false