project:
  type: website
  output-dir: docs

website:
  title: "Ramu Nalla"
  navbar:
    search: true
    collapse: true
    right: 
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "CV"
        href: cv.qmd
      - icon: github
        href: https://github.com/RamuNalla
      - icon: linkedin
        href: https://linkedin.com/in/yourusername

format:
  html:
    theme: [cosmo, custom.scss] # Cosmo is a clean base for typography
    toc: true
    fontsize: 1.05rem
    mainfont: "Inter" # Shreyansh uses clean sans-serif fonts
