project:
  type: website
  output-dir: docs

website:
  title: "Ramu Nalla"
  navbar:
    search: true
    right:
      - text: "About"
        href: index.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - icon: github
        href: https://github.com/RamuNalla
      - icon: linkedin
        href: https://linkedin.com/in/yourusername
  # This adds the moon/sun icon for dark mode toggle
  theme:
    light: [flatly, custom.scss]
    dark: [darkly, custom.scss]

format:
  html:
    toc: false
    mainfont: "Inter"
    link-external-newwindow: true